#!/usr/bin/env python3
"""Convert the ROM-extracted base mazes into the engine Level format.

Inputs:
  reference/base_maze{0,1,2}.bin  — 32x32 VRAM tile grids (unrotated)
  ROM sub-tables (0x2860/0x2A5D/0x2CA5) — start/goal VRAM destinations

Output:
  src/levels/mazes.ts — raw tile grids (CCW-rotated to portrait) + start/goal.
The engine renders the raw tile indices through the ROM tileset, so the maze
graphics are byte-exact; collision treats any non-space, non-marker tile as lethal.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
N = 32
SPACE = 0x2E
FILLER = 0x00
SUBTABLES = [0x2860, 0x2A5D, 0x2CA5]
VRAM = 0x4800


def load_prog() -> bytes:
    d = bytearray()
    for i in range(1, 7):
        d += (ROOT / "rom" / f"cl0{i}.bin").read_bytes()
    return bytes(d)


def ccw(grid):
    # grid[row][col] (N x N) -> portrait[i][j] = grid[j][N-1-i]
    return [[grid[j][N - 1 - i] for j in range(N)] for i in range(N)]


def unrot_to_portrait(off):
    """VRAM offset (unrotated col,row) -> portrait (col,row) after CCW."""
    ocol, orow = off % N, off // N
    return (orow, N - 1 - ocol)  # (portrait_col, portrait_row)


def main() -> int:
    prog = load_prog()
    levels = []
    for i, sub in enumerate(SUBTABLES):
        raw = (ROOT / "reference" / f"base_maze{i}.bin").read_bytes()
        grid = [[raw[r * N + c] for c in range(N)] for r in range(N)]
        port = ccw(grid)  # port[row][col]
        tiles = [port[r][c] for r in range(N) for c in range(N)]

        # start/goal from the marker-draw destinations in the sub-table
        goal_dst = prog[sub + 4] | (prog[sub + 5] << 8)
        start_dst = prog[sub + 6] | (prog[sub + 7] << 8)
        goal = unrot_to_portrait(goal_dst - VRAM)
        start = unrot_to_portrait(start_dst - VRAM)
        levels.append({"tiles": tiles, "start": start, "goal": goal})
        print(f"maze {i}: sub=${sub:04X} goal(c,r)={goal} start(c,r)={start}")

    themes = ["cyan", "magenta", "green"]
    out = ["// AUTO-GENERATED by tools/export_levels.py — byte-exact mazes from ROM.",
           "// Tile grids are 32x32 portrait (ROT90 of VRAM); values index the cl07 ROM",
           "// tileset. SPACE/FILLER render blank; any other tile is lethal on contact.",
           "import type { ColorName } from \"../engine/constants\";", "",
           f"export const MAZE_N = {N};",
           f"export const SPACE_TILE = {SPACE};",
           f"export const FILLER_TILE = {FILLER};", "",
           "export interface RomMaze {",
           "  id: number;",
           "  tiles: Uint8Array;            // MAZE_N*MAZE_N, row-major (portrait)",
           "  start: [col: number, row: number];",
           "  goal: [col: number, row: number];",
           "  theme: ColorName;",
           "}", "",
           "function u8(s: string): Uint8Array {",
           "  const b = atob(s); const a = new Uint8Array(b.length);",
           "  for (let i = 0; i < b.length; i++) a[i] = b.charCodeAt(i);",
           "  return a;",
           "}", "",
           "export const MAZES: RomMaze[] = ["]
    import base64
    for i, lv in enumerate(levels):
        b = base64.b64encode(bytes(lv["tiles"])).decode()
        out.append(f"  {{ id: {i}, theme: \"{themes[i]}\", "
                   f"start: [{lv['start'][0]}, {lv['start'][1]}], "
                   f"goal: [{lv['goal'][0]}, {lv['goal'][1]}], "
                   f"tiles: u8(\"{b}\") }},")
    out.append("];")
    (ROOT / "src" / "levels" / "mazes.ts").write_text("\n".join(out) + "\n")
    print(f"wrote src/levels/mazes.ts ({len(levels)} mazes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
