#!/usr/bin/env python3
"""Export Crazy Balloon ROM tile graphics into a TS data module.

Reads the gfx ROMs (cl07 = gfx1 chars/maze, cl08 = gfx2 sprites) and emits
src/gfx/romTiles.ts containing the raw tile bytes. The engine decodes them at
runtime using the MAME charlayout (8x8, 1bpp, rows bottom-to-top). Keeping the
raw ROM bytes as the source of truth means the graphics ARE the ROM's.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "gfx" / "romTiles.ts"


def b64(data: bytes) -> str:
    import base64
    return base64.b64encode(data).decode("ascii")


def main() -> int:
    cl07 = (ROOT / "rom" / "cl07.bin").read_bytes()
    cl08 = (ROOT / "rom" / "cl08.bin").read_bytes()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// AUTO-GENERATED by tools/export_tiles.py — do not edit by hand.\n"
        "// Raw Crazy Balloon graphics ROM bytes (base64). Decoded at runtime\n"
        "// per MAME charlayout: 8x8, 1bpp, yoffset {7*8..0*8} (rows bottom-to-top).\n\n"
        "function b64ToBytes(s: string): Uint8Array {\n"
        "  const bin = atob(s);\n"
        "  const out = new Uint8Array(bin.length);\n"
        "  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);\n"
        "  return out;\n"
        "}\n\n"
        f'export const GFX1_CHARS = b64ToBytes("{b64(cl07)}"); // cl07.bin\n'
        f'export const GFX2_SPRITES = b64ToBytes("{b64(cl08)}"); // cl08.bin\n\n'
        "export const TILE_W = 8;\n"
        "export const TILE_H = 8;\n"
        "export const TILE_COUNT = 256;\n"
    , encoding="utf-8")
    print(f"wrote {OUT} (cl07={len(cl07)}B, cl08={len(cl08)}B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
